core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("financeiro.urls", namespace="financeiro")),
    path("", include("usuario.urls", namespace="usuario")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

financeiro/urls.py
from django.urls import path, reverse_lazy
from financeiro import views
from django.contrib.auth import views as auth_view

app_name = "financeiro"

urlpatterns = [
    path("", views.Homepage.as_view(), name="index"),
    path("cadastro", views.CadastroTransacao.as_view(), name="cadastro"),
    path("lista_transacao", views.ListaTransacao.as_view(), name="lista_transacao"),
    path("lista_despesa", views.list_despesas, name="lista_despesa"),
    path("lista_receita", views.list_receita, name="lista_receita"),
    path(
        "update_transacao/<int:pk>/",
        views.UpdateTransacao.as_view(),
        name="update_transacao",
    ),
    path(
        "excluir_transacao/<int:pk>/",
        views.DeleteTransacao.as_view(),
        name="excluir_transacao",
    ),
    path("dashboard", views.ListaDashboard.as_view(), name="dashboard"),
  
]

usuario/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = "usuario"

urlpatterns = [
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    # Modulo Usuário
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("cadastro_user/", views.Registrar.as_view(), name="cadastro_user"),
    path(
        "atualiza_usuario/<int:pk>/",
        views.UsuarioUpdate.as_view(),
        name="atualiza_usuario",
    ),
    path(
        "atualiza_usuario/",
        auth_views.PasswordChangeView.as_view(template_name="atualiza_usuario.html"),
        name="atualiza_usuario",
    ),
]

financeiro/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nome")
    description = models.TextField(blank=True, verbose_name="Descrição")

    def __str__(self):
        return self.name


class Transaction(models.Model):
    TRANSACTION_TYPES = [
        ("Despesas", "Despesa"),
        ("Receita", "Receita"),
    ]

    description = models.CharField(
        max_length=255, verbose_name="Descrição da Transação"
    )
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name="Categoria"
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Valor")
    transaction_date = models.DateField(verbose_name="Data do Pagamento")
    transaction_type = models.CharField(
        max_length=10, choices=TRANSACTION_TYPES, verbose_name="Tipo da Transação"
    )

    def __str__(self):
        return self.description
    
    def get_delete_url(self):
        return reverse("financeiro:excluir_transacao", kwargs={"pk": self.pk})

financeiro/forms.py
from django import forms
from .models import Transaction


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ('description','category','amount', 'transaction_date','transaction_type')

usuario/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class UsuarioForm(UserCreationForm):
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

financeiro/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    TemplateView,
    CreateView,
    ListView,
    UpdateView,
    DeleteView,
)
from .forms import TransactionForm
from .models import Transaction, Category
from django.urls import reverse_lazy
from django.db.models import Sum
from financeiro.context_processors import soma_transacao
from django.urls import reverse
from django.shortcuts import get_object_or_404




class Homepage(TemplateView):
    template_name = "index.html"


class CadastroTransacao(LoginRequiredMixin, CreateView):
    template_name = "cadastro.html"
    form_class = TransactionForm
    success_url = reverse_lazy("financeiro:lista_transacao")


class ListaTransacao(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = "lista_transacao.html"


class UpdateTransacao(LoginRequiredMixin, UpdateView):
    template_name = "cadastro.html"
    model = Transaction
    fields = "__all__"
    success_url = reverse_lazy('financeiro:dashboard')


class DeleteTransacao(DeleteView):
    def get_object(self):
        id = self.kwargs.get('pk')
        return get_object_or_404(Transaction, pk=id)
    
    def get_success_url(self):
        return reverse('financeiro:dashboard')


class ListaDashboard(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = "dashboard.html"


def list_despesas(request):
    lista = Transaction.objects.filter(transaction_type="Despesas")
    context = {"lista": lista}
    return render(request, "lista_despesa.html", context)


def list_receita(request):
    lista = Transaction.objects.filter(transaction_type="Receita")
    context = {"lista": lista}
    return render(request, "lista_receita.html", context)

usuario/views.py
from django.views.generic import TemplateView
from .forms import UsuarioForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User


class Registrar(CreateView):
    template_name = "cadastro_user.html"
    form_class = UsuarioForm
    success_url = reverse_lazy("financeiro:index")


class UsuarioUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy("login")
    model = User
    template_name = "atualiza_usuario.html"
    fields = ["first_name", "last_name", "email"]
    success_url = reverse_lazy("financeiro:index")

financeiro/templates/cadastro.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

 
 {% block content  %}
 <div class="row p-5">
    <h2 class= 'text-center p-2 '> <i class="bi bi-cash-coin"></i> <small >Cadastro Despesas e ou Receitas</small></h2>
    <div class="col-md-8 mx-auto bg-ligth shadow-lg p-3 mb-5 ">
       
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}

            <div class="d-grid gap-2 p-4">
              <button type="submit" class=" btn btn-primary btn-lg btn-block"> <i class="bi bi-floppy2-fill"></i> Salvar</button>
            </div>
        </form>
       

    
</div>

  {% endblock  %} 

financeiro/templates/dashboard.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-10 mx-auto">
        <div class="table-responsive">
          <div class="alert alert-success text-center"> Bem Vindo ao seu Dashboard - {{request.user.first_name}}
            {{request.user.last_name}}
          </div>
    <h1 class="text-center bg-light shadow-lg p-2 mb-2">Dashboard Transações Financeiras</h1>

    <style>
  


      .card {
        transition: transform 0.3s;
        box-shadow: 0 9px 10px rgba(0, 0, 0, 0.1);
        margin-bottom: 15px; /* Adicione uma margem inferior para espaçamento entre os cartões */
      }
  
      .card:hover {
        transform: scale(1.25);
      }
    </style>
   
<div class="container mt-5 ">
  <div class="flex-container d-flex flex-wrap">
    
    <div class="flex-item p-4 flex-xl-fill bd-highlight">
        
      <div class="card card border-white card bg-success">
        <div class="card-body">
          <h3 class="card-title text-center text-white border-bottom">Total Receita</h3>
          <p class="card-text"></p>
          <h4 class="card-title text-center text-white ">R$ {{ soma_receitas}}  <i class="bi bi-arrow-up"></i></h4>
          
        </div>
      
      </div>
     
    </div>
    <div class="flex-item p-4 flex-xl-fill bd-highlight">
        
      <div class="card card border-white card bg-danger">
        <div class="card-body">
          <h3 class="card-title text-center text-white border-bottom">Total Despesas  </h3>
          <p class="card-text"></p>
          <h4 class="card-title text-center text-white ">R$ {{ soma_despesas}}   <i class="bi bi-arrow-down"></i></h4>
          
        </div>
      
      </div>
     
    </div>
    <div class="flex-item p-4 flex-xl-fill bd-highlight">
        
      <div class="card card border-white card bg-primary">
        <div class="card-body">
          <h3 class="card-title text-center text-white border-bottom">Total Saldo</h3>
          <p class="card-text"></p>
          <h4 class="card-title text-center text-white ">R$ {{ saldo }}</h4>
         
        </div>
      
      </div>
     
    </div>
    
   
  </div>
 
</div>
    
   <hr>
    <div class="col-md-10 mx-auto">
        
        <div class="table-responsive">

        <h2 class="text-center">Receitas</h2>
        <div class="table-responsive bg-ligth  shadow-lg p-2 mb-5 ">
        <table class='table table-sm table-hover table-bordered border border-5'>
            <thead class="success">
                <tr >
                    <th scope="col">Descrição</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Valor</th>
                    <th scope="col">Data Recebimento</th>
                    <th scope="col">Tipo Transação</th>
                    <th scope="col">Opções</th>
                   
                </tr>
            </thead>
            <tbody>
                {% for transacao in object_list %}
                {% if transacao.transaction_type == 'Receita' %}

                  <tr  class="table-success" >
                    <td>{{ transacao.description }}</td>
                    <td>{{ transacao.category }}</td>
                    <td>R$ {{ transacao.amount }} <i class="bi bi-arrow-up"></i></td>
                    <td>{{ transacao.transaction_date }}</td>
                    <td>{{ transacao.transaction_type }}</td>
                    <td>
                      <a href="{% url "financeiro:update_transacao" transacao.pk %}">
                     <button type="button" class="btn btn-sm btn-outline-primary">Editar <i class="bi bi-pencil"></i></button></a>   
                     
                     <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#modal{{ transacao.pk }}" >Excluir  <i class="bi bi-trash3"></i></button> 
                     <!-- Modal -->
                         <div class=" shadow-lg p-3 mb-5  rounded modal fade" id="modal{{ transacao.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
                           <div class="modal-dialog " role="document">
                             <div class="modal-content ">
                               <div class="modal-header text-center align-items-center p-1 ">
                                 <h4 class="modal-title text-danger w-100 " id="exampleModalLabel">Exclusão </h4>
                                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                   <span aria-hidden="true">&times;</span>
                                 </button>
                               </div>
                               <div class="modal-body ">
                                <h6 class='text-center'> Deseja Realizar a Exclusão do - <strong class= 'text-danger'>"{{ transacao.description}}" ?</strong></h6>  
                               </div>
                               <div class="modal-footer d-flex justify-content-center">
                                 <form method="post" action="{{ transacao.get_delete_url }}">
                                     {% csrf_token %}
                                     <button type="submit" class="btn btn-danger btn-sm ">Excluir </button>
                                 </form>
                                 <button type="button" class="btn btn-secondary btn-sm ml-3 " data-dismiss="modal">Fechar</button>
                             </div>
                             
                             </div>
                           </div>
                         </div>
                      </td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
  </div>
    </div>
</div>
<hr>
<div class="row">
    <d class="col-md-10 mx-auto">
       
        <h2 class="text-center">Despesas</h2>
        <div class="table-responsive shadow-lg p-1 mb-5">
        <table class='table table-sm table-hover table-bordered border border-5'>
            <thead >
                <tr>
                    <th scope="col">Descrição</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Valor</th>
                    <th scope="col">Data Pagamento</th>
                    <th scope="col">Tipo Transação</th>
                    <th scope="col"class= 'text-center'>Opções</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for transacao in object_list %}
                {% if transacao.transaction_type == 'Despesas' %}
                <tr  class="table-danger">
                    <td>{{ transacao.description }}</td>
                    <td>{{ transacao.category }}</td>
                    <td>R$ {{ transacao.amount }} <i class="bi bi-arrow-down"></i></td>
                    <td>{{ transacao.transaction_date }}</td>
                    <td>{{ transacao.transaction_type }}</td>
                    <td>
                      <a href="{% url "financeiro:update_transacao" transacao.pk %}">
                     <button type="button" class="btn btn-sm btn-outline-primary">Editar <i class="bi bi-pencil"></i></button></a> 
                  
                      
                        <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#modal{{ transacao.pk }}" >Excluir  <i class="bi bi-trash3"></i></button> 
                        <!-- Modal -->
                            <div class=" shadow-lg p-3 mb-5  rounded modal fade" id="modal{{ transacao.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
                              <div class="modal-dialog " role="document">
                                <div class="modal-content ">
                                  <div class="modal-header text-center align-items-center p-1 ">
                                    <h4 class="modal-title text-danger w-100 " id="exampleModalLabel">Exclusão </h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-body ">
                                   <h6 class='text-center'> Deseja Realizar a Exclusão do - <strong class= 'text-danger'>"{{ transacao.description}}" ?</strong></h6>  
                                  </div>
                                  <div class="modal-footer d-flex justify-content-center">
                                    <form method="post" action="{{ transacao.get_delete_url }}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger btn-sm ">Excluir </button>
                                    </form>
                                    <button type="button" class="btn btn-secondary btn-sm ml-3 " data-dismiss="modal">Fechar</button>
                                </div>
                                
                                </div>
                              </div>
                            </div>
                      </td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>

  </div>
</div>


{% endblock %}

financeiro/templates/excluir_transacao.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

 
{% block content %}

<div class="row">
    <div class="col-md-4 mx-auto">
        <h2><small class="text-dark" "text-center"></small>Exclusão Transação</h2>
        <hr>
 <form action="" method="POST">
      <p class="text-white">
        Deseja excluir esse Transação: <strong class="text-dark" "text-center"> 
            Você deseja Excluir a Transação do ("{{ object }}")</strong> ?
      </p>
      {% csrf_token %}
      {{ form|crispy }}
      <div class="row">
        <div class="col-6">
          <button type="submit" class="btn btn-success ">SIM</button>
        </div>
        <div class="col-6">
          <a href="{% url 'financeiro:lista_transacao' %}" class="btn btn-danger" title="Voltar">NÃO</a>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

financeiro/templates/lista_receita.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

 
 {% block content  %}
 <div class="row p-5">
    <div class="col-md-10 mx-auto p-2 ">
        <h1 class="text-dark text-center p-2 border-bottom">Transações Financeiras- Receitas</h1>
        <form>
          <div class="input-group mt-2 p-2">
            <input type="text" name='pesquisa_name' class="form-control" placeholder="Pesquisar por Receitas ... ">
            <div class="input-group-append mr-2">
              <button class="btn btn-success btn" type="submit">Pesquisar Receitas</button>
            </div>
          </div>
          </form>

          <div class="d-grid gap-3 p-2 d-md-flex justify-content-md-start ">
            <a href="{% url "financeiro:cadastro" %}">
            <button class="btn btn-outline-primary btn-sm" type="button">Adicionar Nova Receita</button>
            </a>
          </div>
      

      

          <h2 class="text-center">Listas Receitas</h2>
          <div class="table-responsive bg-ligth  shadow-lg p-2 mb-5 ">
  
            <table class="table table-sm table-hover table-bordered border border-5">
              <thead>
              <tr>
                <th scope="col">Descrição</th>
                <th scope="col">Categoria</th>
                <th scope="col">Valor</th>
                <th scope="col">Data</th>
                <th scope="col">Tipo Transação</th>
                <th scope="col">Opções</th>
              </tr>
            </thead>
            
    <tbody>
        {% for l in lista %}
        <tr class="table-success">
                <td>{{ l.description }}</td>
                <td>{{ l.category }}</td>
                <td>R$ {{ l.amount }} <i class="bi bi-arrow-up"> </td>
                <td>{{ l.transaction_date }}</td>
                <td>{{ l.transaction_type}}</td>
                  <td>
                    <a href="{% url "financeiro:update_transacao" l.pk %}">
                   <button type="button" class="btn btn-sm btn-outline-primary">Editar <i class="bi bi-pencil"></i></button></a>   
                   
                   <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#modal{{ l.pk }}" >Excluir <i class="bi bi-trash3"></i></button> 
                   <!-- Modal -->
                       <div class=" shadow-lg p-3 mb-5  rounded modal fade" id="modal{{ l.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
                         <div class="modal-dialog " role="document">
                           <div class="modal-content ">
                             <div class="modal-header text-center align-items-center p-1 ">
                               <h4 class="modal-title text-danger w-100 " id="exampleModalLabel">Exclusão </h4>
                               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                 <span aria-hidden="true">&times;</span>
                               </button>
                             </div>
                             <div class="modal-body ">
                              <h6 class='text-center'> Deseja Realizar a Exclusão do - <strong class= 'text-danger'>"{{ l.description}}" ?</strong></h6>  
                             </div>
                             <div class="modal-footer d-flex justify-content-center">
                               <form method="post" action="{{ l.get_delete_url }}">
                                   {% csrf_token %}
                                   <button type="submit" class="btn btn-danger btn-sm ">Excluir </button>
                               </form>
                               <button type="button" class="btn btn-secondary btn-sm ml-3 " data-dismiss="modal">Fechar</button>
                           </div>
                           
                           </div>
                         </div>
                       </div>
                </td>
              </tr>
        {% empty%}
            <tr>
                <td colspan=" 5">Nenhum campo registrado</td>
            </tr>
        {% endfor %}
        
    </tbody>
    </table>
  </div>
    </div>
</div>

  {% endblock  %} 

financeiro/templates/lista_transacao.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

 
 {% block content  %}
 <div class="row p-5">
    <div class="col-md-10 mx-auto p-2 ">
        <h1 class="text-dark text-center p-2 border-bottom">Transações Despesas/Receitas</h1>
        <form>
          <div class="input-group mt-2 p-2">
            <input type="text" name='pesquisa_name' class="form-control" placeholder="Pesquisar por transações ... ">
            <div class="input-group-append mr-2">
              <button class="btn btn-success btn" type="submit">Pesquisar Transações</button>
            </div>
          </div>
          </form>
        <hr>
        
        <div class="d-grid gap-3 p-2 d-md-flex justify-content-md-start ">
          <a href="{% url "financeiro:cadastro" %}">
          <button class="btn btn-outline-primary btn-sm" type="button">Adicionar Nova Transação</button>
          </a>
        </div>
        <div class="table-responsive bg-ligth  shadow-lg p-2 mb-5 ">
        <table class='table table-sm table-hover table-bordered border border-5'>
          <thead>
              <tr>
                <th scope="col">Descrição</th>
                <th scope="col">Categoria</th>
                <th scope="col">Valor</th>
                <th scope="col">Data</th>
                <th scope="col">Tipo Transação</th>
                <th scope="col">Opções</th>
              </tr>
            </thead>
            
    <tbody>
        {% for transacao in object_list %}
        {% if transacao.transaction_type == 'Despesas' %}
          <tr class="table-danger">

        {% else %}
            <tr class="table-success">
        {% endif %}

            

                <td>{{ transacao.description }}</td>
                <td>{{ transacao.category }}</td>
                {% if transacao.transaction_type == 'Despesas' %}
                  <td>R$ {{ transacao.amount }} <i class="bi bi-arrow-down"></i></td>
                {% else %}
                  <td>R$ {{ transacao.amount }} <i class="bi bi-arrow-up"></i></td>
                {% endif %}
                <td>{{ transacao.transaction_date }}</td>
                <td>{{ transacao.transaction_type}}</td>
                <td>
                  <a href="{% url "financeiro:update_transacao" transacao.pk %}">
                 <button type="button" class="btn btn-sm btn-outline-primary">Editar <i class="bi bi-pencil"></i></button></a>   
                 
                 <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#modal{{ transacao.pk }}" >Excluir <i class="bi bi-trash3"></i></button> 
                 <!-- Modal -->
                     <div class=" shadow-lg p-3 mb-5  rounded modal fade" id="modal{{ transacao.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
                       <div class="modal-dialog " role="document">
                         <div class="modal-content ">
                           <div class="modal-header text-center align-items-center p-1 ">
                             <h4 class="modal-title text-danger w-100 " id="exampleModalLabel">Exclusão </h4>
                             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                               <span aria-hidden="true">&times;</span>
                             </button>
                           </div>
                           <div class="modal-body ">
                            <h6 class='text-center'> Deseja Realizar a Exclusão do - <strong class= 'text-danger'>"{{ transacao.description}}" ?</strong></h6>  
                           </div>
                           <div class="modal-footer d-flex justify-content-center">
                             <form method="post" action="{{ transacao.get_delete_url }}">
                                 {% csrf_token %}
                                 <button type="submit" class="btn btn-danger btn-sm ">Excluir </button>
                             </form>
                             <button type="button" class="btn btn-secondary btn-sm ml-3 " data-dismiss="modal">Fechar</button>
                         </div>
                         
                         </div>
                       </div>
                     </div>
              </td>
                </td>
              </tr>

        {% empty %}
            <tr>
                <td colspan="5">Nenhum campo registrado</td>
            </tr>
        {% endfor %}
        
    </tbody>
    </table>
  </div>
    </div>
</div>
{% endblock %}

templates/footer.html
<title>
    {% block titulo %}
    Finanças
    {% endblock %} 
</title>

templates/navbar.html
{% load static %}
<div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
        <a class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <i class="bi bi-bank me-2"></i> <span class="fms-1 d-none d-sm-inline"> Sistema Finanças</span>
        </a>
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
            <li class="nav-item">
                <a href="{% url "financeiro:index" %}" class="nav-link align-middle px-0">
                    <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                </a>
            </li>
            <li>
                <a href="{% url "financeiro:dashboard" %}" class="nav-link align-middle px-0">
                    <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
               
            </li>
            <li>
                <a href="{% url "financeiro:cadastro" %}" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Cadastros</span></a>
            </li>
        
            <li>
                <a href="{% url "financeiro:lista_transacao" %}" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Transações</span> </a>
                   
                </li>
                    <li>
                        <a href="{% url "financeiro:lista_despesa" %}" class="nav-link px-0"> <span class="d-none d-sm-inline">Lista de Despesas</span> </a>
                    </li>
                    <li>
                        <a href="{% url "financeiro:lista_receita" %}" class="nav-link px-0"> <span class="d-none d-sm-inline"> Lista de Receitas</span> </a>
                    </li>
                </ul>
      
        {% if request.user.is_authenticated %}
        <div class="dropdown pb-4">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="" alt="Foto de Perfil" width="30" height="30" class="rounded-circle" alt="Perfil de Usuário">
                <span class="d-none d-sm-inline mx-1">Olá, {{ request.user.first_name }}</span>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                <li><a class="dropdown-item" href="{% url "usuario:atualiza_usuario" request.user.pk %}">Editar Perfil</a></li>
                <li><a class="dropdown-item" href="{% url "usuario:atualiza_usuario" %}">Alterar Senha</a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url "usuario:logout" %}">Sair</a></li>
            </ul>
        </div>
        {% else %}
        <div class="dropdown pb-4">
            <a href="" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="d-none d-sm-inline mx-1">
                    Acessar
                </span>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                <li><a class="dropdown-item" href="{% url "usuario:cadastro_user" %}">Fazer Cadastro</a></li>
                <li><a class="dropdown-item" href="{% url "usuario:login" %}">Acessar a Conta</a></li>
            </ul>
        </div>
        {% endif %}
    </div>
</div>

usuario/templates/alterasenha.html
<div class="row">
  <div class="col-md-4 mx-auto">
      <h1><small class="text-muted">Alterar Senha</small></h1>
      <h3>Usuario : {{ request.user|upper }} </h3>
<hr>
<form action="" method = "POST">
    {% csrf_token %}
    {{ form|crispy }}

  <button type="submit" class="btn btn-primary"><i class="bi bi-floppy2-fill"></i>Alterar</button><br>

</form>
  </div>
</div>


{% endblock %}

usuario/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container d-flex justify-content-center " style="height: 100vh;">
  <div class="col-md-6  ">
    
      <h3 class="text-center  bg-Secondary shadow-lg p-1 mb-4">Bem Vindo - Sistema de Finanças Pessoais</h3>
   
    <h4 class="text-center"><i class="bi bi-bag-fill"></i> <small class="border-start-0 text-dark"> AUTENTICAÇÃO USUÁRIO</small></h4>
    <hr>
    <form action="" method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
        <label class="form-check-label" for="flexCheckChecked">
          Lembra-me
        </label>
      </div>
      <button type="submit" class="btn btn-primary"><i class="bi bi-floppy2-fill"></i> Acessar Sistema</button>
      </div>
      <a href="{% url "usuario:cadastro_user" %}" class="link-primary"><i class="bi bi-plus-square-dotted"></i> Fazer Cadastro</a>
    </form>
  </div>
</div>
{% endblock %}